///////////////////////////////////////////////////////////
//  ItemCats.cs
//  Implementation of the Class ItemCats
//  Generated by Enterprise Architect
//  Created on:      08-五月-2013 0:20:07
//  Original author: 吉桂昕
///////////////////////////////////////////////////////////

using MyTools.TaoBao.Interface;

namespace MyTools.TaoBao.Impl
{
    /// <summary>
    ///     通过已配置好的Cid,Props表中获取数据
    /// </summary>
    public class ItemCats : IItemCats
    {
        /// <summary>
        ///     根据店铺的父类目和子类目->获取后台供卖家发布商品的标准商品类目id
        /// </summary>
        /// <param name="childCatalog">子类目</param>
        /// <param name="parentCatalog">父类目</param>
        public string GetCid(string childCatalog, string parentCatalog)
        {
            return "";
        }

        /// <summary>
        ///     通过Cid得到相应的props
        /// </summary>
        /// <param name="cid">淘宝所属类目ID</param>
        public string GetPropsByCid(string cid)
        {
            return "";
        }

        ~ItemCats()
        {
        }

        public virtual void Dispose()
        {
        }
    }
}

//end ItemCats