///////////////////////////////////////////////////////////
//  IItemCats.cs
//  Implementation of the Interface IItemCats
//  Generated by Enterprise Architect
//  Created on:      08-五月-2013 0:20:04
//  Original author: 吉桂昕
///////////////////////////////////////////////////////////
namespace MyTools.TaoBao.Interface
{
    /// <summary>
    /// 根据该商品所属的父类目和子类目来得到，cid和props
    /// </summary>
    public interface IItemCats  {

        /// <summary>
        /// 根据店铺的父类目和子类目->获取后台供卖家发布商品的标准商品类目id
        /// </summary>
        /// <param name="childCatalog">子类目</param>
        /// <param name="parentCatalog">父类目</param>
        string GetCid(string childCatalog, string parentCatalog);

        /// <summary>
        /// 通过Cid得到相应的props
        /// </summary>
        /// <param name="cid">淘宝所属类目ID</param>
        string GetPropsByCid(string cid);
    }
}//end IItemCats